package com.kingroot.sdk.root; class k { void a() { int a;
a=0;// .class final Lcom/kingroot/sdk/root/k;
a=0;// .super Ljava/lang/Object;
a=0;// .source "SourceFile"
a=0;// 
a=0;// 
a=0;// # instance fields
a=0;// .field a:Ljava/lang/String;
a=0;// 
a=0;// .field b:Ljava/lang/String;
a=0;// 
a=0;// .field c:[Ljava/lang/Class;
a=0;// 
a=0;// .field d:Ljava/lang/String;
a=0;// 
a=0;// .field e:[Ljava/lang/Class;
a=0;// 
a=0;// .field f:Ljava/lang/String;
a=0;// 
a=0;// .field g:[Ljava/lang/Class;
a=0;// 
a=0;// .field h:Ljava/lang/String;
a=0;// 
a=0;// .field i:[Ljava/lang/Class;
a=0;// 
a=0;// .field j:Ljava/lang/String;
a=0;// 
a=0;// .field k:[Ljava/lang/Class;
a=0;// 
a=0;// .field l:Ljava/lang/String;
a=0;// 
a=0;// .field m:[Ljava/lang/Class;
a=0;// 
a=0;// .field n:Ljava/lang/String;
a=0;// 
a=0;// .field o:[Ljava/lang/Class;
a=0;// 
a=0;// 
a=0;// # direct methods
a=0;// .method constructor <init>()V
a=0;//     .locals 6
a=0;// 
a=0;//     .prologue
a=0;//     const/4 v5, 0x3
a=0;// 
a=0;//     #v5=(PosByte);
a=0;//     const/4 v4, 0x2
a=0;// 
a=0;//     #v4=(PosByte);
a=0;//     const/4 v3, 0x1
a=0;// 
a=0;//     #v3=(One);
a=0;//     const/4 v2, 0x0
a=0;// 
a=0;//     .line 51
a=0;//     #v2=(Null);
a=0;//     invoke-direct {p0}, Ljava/lang/Object;-><init>()V
a=0;// 
a=0;//     .line 53
a=0;//     #p0=(Reference,Lcom/kingroot/sdk/root/k;);
a=0;//     const-string v0, "krsdk.XSolution"
a=0;// 
a=0;//     #v0=(Reference,Ljava/lang/String;);
a=0;//     iput-object v0, p0, Lcom/kingroot/sdk/root/k;->a:Ljava/lang/String;
a=0;// 
a=0;//     .line 55
a=0;//     const-string v0, "init"
a=0;// 
a=0;//     iput-object v0, p0, Lcom/kingroot/sdk/root/k;->b:Ljava/lang/String;
a=0;// 
a=0;//     .line 56
a=0;//     new-array v0, v5, [Ljava/lang/Class;
a=0;// 
a=0;//     const-class v1, Landroid/content/Context;
a=0;// 
a=0;//     #v1=(Reference,Ljava/lang/Class;);
a=0;//     aput-object v1, v0, v2
a=0;// 
a=0;//     const-class v1, Ljava/lang/String;
a=0;// 
a=0;//     aput-object v1, v0, v3
a=0;// 
a=0;//     const-class v1, Ljava/lang/ClassLoader;
a=0;// 
a=0;//     aput-object v1, v0, v4
a=0;// 
a=0;//     iput-object v0, p0, Lcom/kingroot/sdk/root/k;->c:[Ljava/lang/Class;
a=0;// 
a=0;//     .line 58
a=0;//     const-string v0, "root"
a=0;// 
a=0;//     iput-object v0, p0, Lcom/kingroot/sdk/root/k;->d:Ljava/lang/String;
a=0;// 
a=0;//     .line 59
a=0;//     new-array v0, v3, [Ljava/lang/Class;
a=0;// 
a=0;//     const-class v1, Landroid/content/Context;
a=0;// 
a=0;//     aput-object v1, v0, v2
a=0;// 
a=0;//     iput-object v0, p0, Lcom/kingroot/sdk/root/k;->e:[Ljava/lang/Class;
a=0;// 
a=0;//     .line 61
a=0;//     const-string v0, "destroy"
a=0;// 
a=0;//     iput-object v0, p0, Lcom/kingroot/sdk/root/k;->f:Ljava/lang/String;
a=0;// 
a=0;//     .line 62
a=0;//     new-array v0, v3, [Ljava/lang/Class;
a=0;// 
a=0;//     const-class v1, Landroid/content/Context;
a=0;// 
a=0;//     aput-object v1, v0, v2
a=0;// 
a=0;//     iput-object v0, p0, Lcom/kingroot/sdk/root/k;->g:[Ljava/lang/Class;
a=0;// 
a=0;//     .line 64
a=0;//     const-string v0, "getShell"
a=0;// 
a=0;//     iput-object v0, p0, Lcom/kingroot/sdk/root/k;->h:Ljava/lang/String;
a=0;// 
a=0;//     .line 65
a=0;//     new-array v0, v2, [Ljava/lang/Class;
a=0;// 
a=0;//     iput-object v0, p0, Lcom/kingroot/sdk/root/k;->i:[Ljava/lang/Class;
a=0;// 
a=0;//     .line 67
a=0;//     const-string v0, "executeCommand"
a=0;// 
a=0;//     iput-object v0, p0, Lcom/kingroot/sdk/root/k;->j:Ljava/lang/String;
a=0;// 
a=0;//     .line 68
a=0;//     new-array v0, v4, [Ljava/lang/Class;
a=0;// 
a=0;//     const-class v1, Ljava/lang/Object;
a=0;// 
a=0;//     aput-object v1, v0, v2
a=0;// 
a=0;//     const-class v1, Ljava/lang/String;
a=0;// 
a=0;//     aput-object v1, v0, v3
a=0;// 
a=0;//     iput-object v0, p0, Lcom/kingroot/sdk/root/k;->k:[Ljava/lang/Class;
a=0;// 
a=0;//     .line 70
a=0;//     const-string v0, "closeShell"
a=0;// 
a=0;//     iput-object v0, p0, Lcom/kingroot/sdk/root/k;->l:Ljava/lang/String;
a=0;// 
a=0;//     .line 71
a=0;//     new-array v0, v3, [Ljava/lang/Class;
a=0;// 
a=0;//     const-class v1, Ljava/lang/Object;
a=0;// 
a=0;//     aput-object v1, v0, v2
a=0;// 
a=0;//     iput-object v0, p0, Lcom/kingroot/sdk/root/k;->m:[Ljava/lang/Class;
a=0;// 
a=0;//     .line 73
a=0;//     const-string v0, "init2"
a=0;// 
a=0;//     iput-object v0, p0, Lcom/kingroot/sdk/root/k;->n:Ljava/lang/String;
a=0;// 
a=0;//     .line 74
a=0;//     new-array v0, v5, [Ljava/lang/Class;
a=0;// 
a=0;//     const-class v1, Landroid/content/Context;
a=0;// 
a=0;//     aput-object v1, v0, v2
a=0;// 
a=0;//     const-class v1, Ljava/lang/ClassLoader;
a=0;// 
a=0;//     aput-object v1, v0, v3
a=0;// 
a=0;//     const-class v1, Ljava/util/HashMap;
a=0;// 
a=0;//     aput-object v1, v0, v4
a=0;// 
a=0;//     iput-object v0, p0, Lcom/kingroot/sdk/root/k;->o:[Ljava/lang/Class;
a=0;// 
a=0;//     .line 51
a=0;//     return-void
a=0;// .end method
}}
