package com.kingroot.RushRoot; class af { void a() { int a;
a=0;// .class public interface abstract Lcom/kingroot/RushRoot/af;
a=0;// .super Ljava/lang/Object;
a=0;// .source "SourceFile"
a=0;// 
a=0;// 
a=0;// # virtual methods
a=0;// .method public abstract a()V
a=0;// .end method
a=0;// 
a=0;// .method public abstract a(I)V
a=0;// .end method
a=0;// 
a=0;// .method public abstract a(Lcom/kingroot/RushRoot/gx;)V
a=0;// .end method
a=0;// 
a=0;// .method public abstract a([I)V
a=0;// .end method
a=0;// 
a=0;// .method public abstract b()V
a=0;// .end method
a=0;// 
a=0;// .method public abstract b(I)V
a=0;// .end method
a=0;// 
a=0;// .method public abstract b(Lcom/kingroot/RushRoot/gx;)V
a=0;// .end method
a=0;// 
a=0;// .method public abstract c()V
a=0;// .end method
a=0;// 
a=0;// .method public abstract c(Lcom/kingroot/RushRoot/gx;)V
a=0;// .end method
a=0;// 
a=0;// .method public abstract d()V
a=0;// .end method
a=0;// 
a=0;// .method public abstract e()V
a=0;// .end method
a=0;// 
a=0;// .method public abstract f()V
a=0;// .end method
a=0;// 
a=0;// .method public abstract g()V
a=0;// .end method
a=0;// 
a=0;// .method public abstract h()V
a=0;// .end method
a=0;// 
a=0;// .method public abstract i()V
a=0;// .end method
}}
