package com.kingroot.RushRoot; class cn { void a() { int a;
a=0;// .class final Lcom/kingroot/RushRoot/cn;
a=0;// .super Ljava/lang/Object;
a=0;// .source "SourceFile"
a=0;// 
a=0;// # interfaces
a=0;// .implements Landroid/view/animation/Animation$AnimationListener;
a=0;// 
a=0;// 
a=0;// # instance fields
a=0;// .field final synthetic a:Landroid/view/View;
a=0;// 
a=0;// .field final synthetic b:I
a=0;// 
a=0;// .field final synthetic c:Lcom/kingroot/RushRoot/co;
a=0;// 
a=0;// 
a=0;// # direct methods
a=0;// .method constructor <init>(Landroid/view/View;)V
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 71
a=0;//     iput-object p1, p0, Lcom/kingroot/RushRoot/cn;->a:Landroid/view/View;
a=0;// 
a=0;//     const/4 v0, 0x0
a=0;// 
a=0;//     #v0=(Null);
a=0;//     iput v0, p0, Lcom/kingroot/RushRoot/cn;->b:I
a=0;// 
a=0;//     const/4 v0, 0x0
a=0;// 
a=0;//     iput-object v0, p0, Lcom/kingroot/RushRoot/cn;->c:Lcom/kingroot/RushRoot/co;
a=0;// 
a=0;//     invoke-direct {p0}, Ljava/lang/Object;-><init>()V
a=0;// 
a=0;//     #p0=(Reference,Lcom/kingroot/RushRoot/cn;);
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// 
a=0;// # virtual methods
a=0;// .method public final onAnimationEnd(Landroid/view/animation/Animation;)V
a=0;//     .locals 2
a=0;// 
a=0;//     .prologue
a=0;//     .line 83
a=0;//     const-string v0, "onAnimationEnd"
a=0;// 
a=0;//     #v0=(Reference,Ljava/lang/String;);
a=0;//     invoke-static {v0}, Lcom/kingroot/RushRoot/br;->a(Ljava/lang/String;)V
a=0;// 
a=0;//     .line 84
a=0;//     iget-object v0, p0, Lcom/kingroot/RushRoot/cn;->a:Landroid/view/View;
a=0;// 
a=0;//     iget v1, p0, Lcom/kingroot/RushRoot/cn;->b:I
a=0;// 
a=0;//     #v1=(Integer);
a=0;//     invoke-virtual {v0, v1}, Landroid/view/View;->setVisibility(I)V
a=0;// 
a=0;//     .line 85
a=0;//     iget-object v0, p0, Lcom/kingroot/RushRoot/cn;->c:Lcom/kingroot/RushRoot/co;
a=0;// 
a=0;//     if-eqz v0, :cond_0
a=0;// 
a=0;//     .line 86
a=0;//     iget-object v0, p0, Lcom/kingroot/RushRoot/cn;->c:Lcom/kingroot/RushRoot/co;
a=0;// 
a=0;//     .line 88
a=0;//     :cond_0
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public final onAnimationRepeat(Landroid/view/animation/Animation;)V
a=0;//     .locals 0
a=0;// 
a=0;//     .prologue
a=0;//     .line 79
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public final onAnimationStart(Landroid/view/animation/Animation;)V
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 74
a=0;//     const-string v0, "onAnimationStart"
a=0;// 
a=0;//     #v0=(Reference,Ljava/lang/String;);
a=0;//     invoke-static {v0}, Lcom/kingroot/RushRoot/br;->a(Ljava/lang/String;)V
a=0;// 
a=0;//     .line 75
a=0;//     return-void
a=0;// .end method
}}
