package com.kingroot.RushRoot; class cr { void a() { int a;
a=0;// .class final Lcom/kingroot/RushRoot/cr;
a=0;// .super Lcom/kingroot/RushRoot/cp;
a=0;// .source "SourceFile"
a=0;// 
a=0;// 
a=0;// # instance fields
a=0;// .field final synthetic a:Lcom/kingroot/RushRoot/ct;
a=0;// 
a=0;// .field final synthetic b:Lcom/kingroot/RushRoot/cq;
a=0;// 
a=0;// 
a=0;// # direct methods
a=0;// .method constructor <init>(Lcom/kingroot/RushRoot/cq;Lcom/kingroot/RushRoot/ct;)V
a=0;//     .locals 0
a=0;// 
a=0;//     .prologue
a=0;//     .line 41
a=0;//     iput-object p1, p0, Lcom/kingroot/RushRoot/cr;->b:Lcom/kingroot/RushRoot/cq;
a=0;// 
a=0;//     iput-object p2, p0, Lcom/kingroot/RushRoot/cr;->a:Lcom/kingroot/RushRoot/ct;
a=0;// 
a=0;//     invoke-direct {p0}, Lcom/kingroot/RushRoot/cp;-><init>()V
a=0;// 
a=0;//     #p0=(Reference,Lcom/kingroot/RushRoot/cr;);
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// 
a=0;// # virtual methods
a=0;// .method public final onAnimationEnd(Landroid/view/animation/Animation;)V
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 44
a=0;//     iget-object v0, p0, Lcom/kingroot/RushRoot/cr;->a:Lcom/kingroot/RushRoot/ct;
a=0;// 
a=0;//     #v0=(Reference,Lcom/kingroot/RushRoot/ct;);
a=0;//     if-eqz v0, :cond_0
a=0;// 
a=0;//     .line 45
a=0;//     iget-object v0, p0, Lcom/kingroot/RushRoot/cr;->a:Lcom/kingroot/RushRoot/ct;
a=0;// 
a=0;//     invoke-interface {v0}, Lcom/kingroot/RushRoot/ct;->a()V
a=0;// 
a=0;//     .line 47
a=0;//     :cond_0
a=0;//     return-void
a=0;// .end method
}}
