package com.kingroot.RushRoot; class cz { void a() { int a;
a=0;// .class final Lcom/kingroot/RushRoot/cz;
a=0;// .super Lcom/kingroot/RushRoot/cp;
a=0;// .source "SourceFile"
a=0;// 
a=0;// 
a=0;// # instance fields
a=0;// .field final synthetic a:Lcom/kingroot/RushRoot/db;
a=0;// 
a=0;// .field final synthetic b:Lcom/kingroot/RushRoot/cx;
a=0;// 
a=0;// 
a=0;// # direct methods
a=0;// .method constructor <init>(Lcom/kingroot/RushRoot/cx;Lcom/kingroot/RushRoot/db;)V
a=0;//     .locals 0
a=0;// 
a=0;//     .prologue
a=0;//     .line 56
a=0;//     iput-object p1, p0, Lcom/kingroot/RushRoot/cz;->b:Lcom/kingroot/RushRoot/cx;
a=0;// 
a=0;//     iput-object p2, p0, Lcom/kingroot/RushRoot/cz;->a:Lcom/kingroot/RushRoot/db;
a=0;// 
a=0;//     invoke-direct {p0}, Lcom/kingroot/RushRoot/cp;-><init>()V
a=0;// 
a=0;//     #p0=(Reference,Lcom/kingroot/RushRoot/cz;);
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// 
a=0;// # virtual methods
a=0;// .method public final onAnimationEnd(Landroid/view/animation/Animation;)V
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 59
a=0;//     iget-object v0, p0, Lcom/kingroot/RushRoot/cz;->a:Lcom/kingroot/RushRoot/db;
a=0;// 
a=0;//     #v0=(Reference,Lcom/kingroot/RushRoot/db;);
a=0;//     if-eqz v0, :cond_0
a=0;// 
a=0;//     .line 60
a=0;//     iget-object v0, p0, Lcom/kingroot/RushRoot/cz;->a:Lcom/kingroot/RushRoot/db;
a=0;// 
a=0;//     invoke-interface {v0}, Lcom/kingroot/RushRoot/db;->a()V
a=0;// 
a=0;//     .line 62
a=0;//     :cond_0
a=0;//     return-void
a=0;// .end method
}}
