package com.kingroot.RushRoot; class de { void a() { int a;
a=0;// .class public abstract Lcom/kingroot/RushRoot/de;
a=0;// .super Lcom/kingroot/RushRoot/cx;
a=0;// .source "SourceFile"
a=0;// 
a=0;// 
a=0;// # instance fields
a=0;// .field protected a:Landroid/widget/ImageView;
a=0;// 
a=0;// .field protected b:Landroid/widget/TextView;
a=0;// 
a=0;// .field protected c:Landroid/widget/TextView;
a=0;// 
a=0;// .field protected d:I
a=0;// 
a=0;// 
a=0;// # direct methods
a=0;// .method public constructor <init>(Landroid/content/Context;)V
a=0;//     .locals 2
a=0;// 
a=0;//     .prologue
a=0;//     .line 19
a=0;//     invoke-direct {p0, p1}, Lcom/kingroot/RushRoot/cx;-><init>(Landroid/content/Context;)V
a=0;// 
a=0;//     .line 16
a=0;//     #p0=(Reference,Lcom/kingroot/RushRoot/de;);
a=0;//     const/4 v0, -0x1
a=0;// 
a=0;//     #v0=(Byte);
a=0;//     iput v0, p0, Lcom/kingroot/RushRoot/de;->d:I
a=0;// 
a=0;//     .line 21
a=0;//     invoke-virtual {p0}, Lcom/kingroot/RushRoot/de;->f()Landroid/view/View;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     #v0=(Reference,Landroid/view/View;);
a=0;//     const v1, 0x7f050031
a=0;// 
a=0;//     #v1=(Integer);
a=0;//     invoke-virtual {v0, v1}, Landroid/view/View;->findViewById(I)Landroid/view/View;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     check-cast v0, Landroid/widget/ImageView;
a=0;// 
a=0;//     iput-object v0, p0, Lcom/kingroot/RushRoot/de;->a:Landroid/widget/ImageView;
a=0;// 
a=0;//     .line 22
a=0;//     invoke-virtual {p0}, Lcom/kingroot/RushRoot/de;->f()Landroid/view/View;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     const v1, 0x7f050032
a=0;// 
a=0;//     invoke-virtual {v0, v1}, Landroid/view/View;->findViewById(I)Landroid/view/View;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     check-cast v0, Landroid/widget/TextView;
a=0;// 
a=0;//     iput-object v0, p0, Lcom/kingroot/RushRoot/de;->b:Landroid/widget/TextView;
a=0;// 
a=0;//     .line 23
a=0;//     invoke-virtual {p0}, Lcom/kingroot/RushRoot/de;->f()Landroid/view/View;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     const v1, 0x7f050033
a=0;// 
a=0;//     invoke-virtual {v0, v1}, Landroid/view/View;->findViewById(I)Landroid/view/View;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     check-cast v0, Landroid/widget/TextView;
a=0;// 
a=0;//     iput-object v0, p0, Lcom/kingroot/RushRoot/de;->c:Landroid/widget/TextView;
a=0;// 
a=0;//     .line 26
a=0;//     invoke-virtual {p0}, Lcom/kingroot/RushRoot/de;->e()I
a=0;// 
a=0;//     move-result v0
a=0;// 
a=0;//     .line 27
a=0;//     #v0=(Integer);
a=0;//     iget v1, p0, Lcom/kingroot/RushRoot/de;->d:I
a=0;// 
a=0;//     if-eq v0, v1, :cond_0
a=0;// 
a=0;//     .line 28
a=0;//     invoke-virtual {p0}, Lcom/kingroot/RushRoot/de;->f()Landroid/view/View;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     #v0=(Reference,Landroid/view/View;);
a=0;//     invoke-virtual {p0}, Lcom/kingroot/RushRoot/de;->e()I
a=0;// 
a=0;//     move-result v1
a=0;// 
a=0;//     invoke-virtual {v0, v1}, Landroid/view/View;->setBackgroundResource(I)V
a=0;// 
a=0;//     .line 31
a=0;//     :cond_0
a=0;//     #v0=(Conflicted);
a=0;//     iget-object v0, p0, Lcom/kingroot/RushRoot/de;->a:Landroid/widget/ImageView;
a=0;// 
a=0;//     #v0=(Reference,Landroid/widget/ImageView;);
a=0;//     invoke-virtual {p0, v0}, Lcom/kingroot/RushRoot/de;->a(Landroid/widget/ImageView;)V
a=0;// 
a=0;//     .line 32
a=0;//     iget-object v0, p0, Lcom/kingroot/RushRoot/de;->b:Landroid/widget/TextView;
a=0;// 
a=0;//     invoke-virtual {p0, v0}, Lcom/kingroot/RushRoot/de;->b(Landroid/widget/TextView;)V
a=0;// 
a=0;//     .line 33
a=0;//     iget-object v0, p0, Lcom/kingroot/RushRoot/de;->c:Landroid/widget/TextView;
a=0;// 
a=0;//     invoke-virtual {p0, v0}, Lcom/kingroot/RushRoot/de;->a(Landroid/widget/TextView;)V
a=0;// 
a=0;//     .line 34
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// 
a=0;// # virtual methods
a=0;// .method protected a()Landroid/view/View;
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 38
a=0;//     const v0, 0x7f03000c
a=0;// 
a=0;//     #v0=(Integer);
a=0;//     invoke-virtual {p0, v0}, Lcom/kingroot/RushRoot/de;->b(I)Landroid/view/View;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     #v0=(Reference,Landroid/view/View;);
a=0;//     return-object v0
a=0;// .end method
a=0;// 
a=0;// .method protected a(Landroid/widget/ImageView;)V
a=0;//     .locals 0
a=0;// 
a=0;//     .prologue
a=0;//     .line 54
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method protected a(Landroid/widget/TextView;)V
a=0;//     .locals 2
a=0;// 
a=0;//     .prologue
a=0;//     .line 46
a=0;//     new-instance v0, Ljava/lang/StringBuilder;
a=0;// 
a=0;//     #v0=(UninitRef,Ljava/lang/StringBuilder;);
a=0;//     invoke-direct {v0}, Ljava/lang/StringBuilder;-><init>()V
a=0;// 
a=0;//     #v0=(Reference,Ljava/lang/StringBuilder;);
a=0;//     const v1, 0x7f080020
a=0;// 
a=0;//     #v1=(Integer);
a=0;//     invoke-virtual {p0, v1}, Lcom/kingroot/RushRoot/de;->d(I)Ljava/lang/String;
a=0;// 
a=0;//     move-result-object v1
a=0;// 
a=0;//     #v1=(Reference,Ljava/lang/String;);
a=0;//     invoke-virtual {v0, v1}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     invoke-static {}, Lcom/kingroot/RushRoot/ck;->a()Ljava/lang/String;
a=0;// 
a=0;//     move-result-object v1
a=0;// 
a=0;//     invoke-virtual {v0, v1}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     invoke-virtual {v0}, Ljava/lang/StringBuilder;->toString()Ljava/lang/String;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     invoke-virtual {p1, v0}, Landroid/widget/TextView;->setText(Ljava/lang/CharSequence;)V
a=0;// 
a=0;//     .line 48
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method protected b(Landroid/widget/TextView;)V
a=0;//     .locals 0
a=0;// 
a=0;//     .prologue
a=0;//     .line 51
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method protected e()I
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 42
a=0;//     const v0, 0x7f02001b
a=0;// 
a=0;//     #v0=(Integer);
a=0;//     return v0
a=0;// .end method
}}
