package com.kingroot.RushRoot; class dr { void a() { int a;
a=0;// .class final Lcom/kingroot/RushRoot/dr;
a=0;// .super Lcom/kingroot/RushRoot/cp;
a=0;// .source "SourceFile"
a=0;// 
a=0;// 
a=0;// # instance fields
a=0;// .field final synthetic a:Ljava/lang/String;
a=0;// 
a=0;// .field final synthetic b:Landroid/view/animation/AnimationSet;
a=0;// 
a=0;// .field final synthetic c:Lcom/kingroot/RushRoot/dp;
a=0;// 
a=0;// 
a=0;// # direct methods
a=0;// .method constructor <init>(Lcom/kingroot/RushRoot/dp;Ljava/lang/String;Landroid/view/animation/AnimationSet;)V
a=0;//     .locals 0
a=0;// 
a=0;//     .prologue
a=0;//     .line 92
a=0;//     iput-object p1, p0, Lcom/kingroot/RushRoot/dr;->c:Lcom/kingroot/RushRoot/dp;
a=0;// 
a=0;//     iput-object p2, p0, Lcom/kingroot/RushRoot/dr;->a:Ljava/lang/String;
a=0;// 
a=0;//     iput-object p3, p0, Lcom/kingroot/RushRoot/dr;->b:Landroid/view/animation/AnimationSet;
a=0;// 
a=0;//     invoke-direct {p0}, Lcom/kingroot/RushRoot/cp;-><init>()V
a=0;// 
a=0;//     #p0=(Reference,Lcom/kingroot/RushRoot/dr;);
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// 
a=0;// # virtual methods
a=0;// .method public final onAnimationEnd(Landroid/view/animation/Animation;)V
a=0;//     .locals 2
a=0;// 
a=0;//     .prologue
a=0;//     .line 95
a=0;//     iget-object v0, p0, Lcom/kingroot/RushRoot/dr;->c:Lcom/kingroot/RushRoot/dp;
a=0;// 
a=0;//     #v0=(Reference,Lcom/kingroot/RushRoot/dp;);
a=0;//     invoke-static {v0}, Lcom/kingroot/RushRoot/dp;->d(Lcom/kingroot/RushRoot/dp;)Landroid/widget/TextView;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     iget-object v1, p0, Lcom/kingroot/RushRoot/dr;->a:Ljava/lang/String;
a=0;// 
a=0;//     #v1=(Reference,Ljava/lang/String;);
a=0;//     invoke-virtual {v0, v1}, Landroid/widget/TextView;->setText(Ljava/lang/CharSequence;)V
a=0;// 
a=0;//     .line 96
a=0;//     iget-object v0, p0, Lcom/kingroot/RushRoot/dr;->c:Lcom/kingroot/RushRoot/dp;
a=0;// 
a=0;//     invoke-static {v0}, Lcom/kingroot/RushRoot/dp;->e(Lcom/kingroot/RushRoot/dp;)Landroid/view/View;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     iget-object v1, p0, Lcom/kingroot/RushRoot/dr;->b:Landroid/view/animation/AnimationSet;
a=0;// 
a=0;//     invoke-virtual {v0, v1}, Landroid/view/View;->startAnimation(Landroid/view/animation/Animation;)V
a=0;// 
a=0;//     .line 97
a=0;//     iget-object v0, p0, Lcom/kingroot/RushRoot/dr;->c:Lcom/kingroot/RushRoot/dp;
a=0;// 
a=0;//     invoke-static {v0}, Lcom/kingroot/RushRoot/dp;->d(Lcom/kingroot/RushRoot/dp;)Landroid/widget/TextView;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     iget-object v1, p0, Lcom/kingroot/RushRoot/dr;->b:Landroid/view/animation/AnimationSet;
a=0;// 
a=0;//     invoke-virtual {v0, v1}, Landroid/widget/TextView;->startAnimation(Landroid/view/animation/Animation;)V
a=0;// 
a=0;//     .line 98
a=0;//     return-void
a=0;// .end method
}}
