package com.kingroot.RushRoot; class ew { void a() { int a;
a=0;// .class final Lcom/kingroot/RushRoot/ew;
a=0;// .super Ljava/lang/Thread;
a=0;// .source "SourceFile"
a=0;// 
a=0;// 
a=0;// # instance fields
a=0;// .field final synthetic a:Lcom/kingroot/RushRoot/et;
a=0;// 
a=0;// .field private final synthetic b:Ljava/lang/String;
a=0;// 
a=0;// 
a=0;// # direct methods
a=0;// .method constructor <init>(Lcom/kingroot/RushRoot/et;Ljava/lang/String;)V
a=0;//     .locals 0
a=0;// 
a=0;//     .prologue
a=0;//     .line 1
a=0;//     iput-object p1, p0, Lcom/kingroot/RushRoot/ew;->a:Lcom/kingroot/RushRoot/et;
a=0;// 
a=0;//     iput-object p2, p0, Lcom/kingroot/RushRoot/ew;->b:Ljava/lang/String;
a=0;// 
a=0;//     .line 96
a=0;//     invoke-direct {p0}, Ljava/lang/Thread;-><init>()V
a=0;// 
a=0;//     #p0=(Reference,Lcom/kingroot/RushRoot/ew;);
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// 
a=0;// # virtual methods
a=0;// .method public final run()V
a=0;//     .locals 6
a=0;// 
a=0;//     .prologue
a=0;//     const/4 v5, 0x1
a=0;// 
a=0;//     .line 100
a=0;//     #v5=(One);
a=0;//     invoke-static {}, Lcom/kingroot/RushRoot/fc;->b()Ljava/lang/String;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     #v0=(Reference,Ljava/lang/String;);
a=0;//     const/4 v1, 0x3
a=0;// 
a=0;//     .line 99
a=0;//     #v1=(PosByte);
a=0;//     invoke-static {v0, v1}, Lcom/kingroot/sdk/root/l;->a(Ljava/lang/String;I)Lcom/kingroot/sdk/root/l;
a=0;// 
a=0;//     move-result-object v1
a=0;// 
a=0;//     .line 102
a=0;//     :try_start_0
a=0;//     #v1=(Reference,Lcom/kingroot/sdk/root/l;);
a=0;//     new-instance v0, Ljava/lang/StringBuilder;
a=0;// 
a=0;//     #v0=(UninitRef,Ljava/lang/StringBuilder;);
a=0;//     iget-object v2, p0, Lcom/kingroot/RushRoot/ew;->b:Ljava/lang/String;
a=0;// 
a=0;//     #v2=(Reference,Ljava/lang/String;);
a=0;//     invoke-static {v2}, Ljava/lang/String;->valueOf(Ljava/lang/Object;)Ljava/lang/String;
a=0;// 
a=0;//     move-result-object v2
a=0;// 
a=0;//     invoke-direct {v0, v2}, Ljava/lang/StringBuilder;-><init>(Ljava/lang/String;)V
a=0;// 
a=0;//     #v0=(Reference,Ljava/lang/StringBuilder;);
a=0;//     const-string v2, " scanner: wait for lock"
a=0;// 
a=0;//     invoke-virtual {v0, v2}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     invoke-virtual {v0}, Ljava/lang/StringBuilder;->toString()Ljava/lang/String;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     invoke-static {v0}, Lcom/kingroot/RushRoot/fe;->a(Ljava/lang/String;)V
a=0;// 
a=0;//     .line 103
a=0;//     invoke-static {}, Lcom/kingroot/RushRoot/et;->f()Ljava/lang/Object;
a=0;// 
a=0;//     move-result-object v2
a=0;// 
a=0;//     monitor-enter v2
a=0;//     :try_end_0
a=0;//     .catch Ljava/lang/Exception; {:try_start_0 .. :try_end_0} :catch_0
a=0;// 
a=0;//     .line 104
a=0;//     :try_start_1
a=0;//     new-instance v0, Ljava/lang/StringBuilder;
a=0;// 
a=0;//     #v0=(UninitRef,Ljava/lang/StringBuilder;);
a=0;//     const-string v3, "START: scan "
a=0;// 
a=0;//     #v3=(Reference,Ljava/lang/String;);
a=0;//     invoke-direct {v0, v3}, Ljava/lang/StringBuilder;-><init>(Ljava/lang/String;)V
a=0;// 
a=0;//     #v0=(Reference,Ljava/lang/StringBuilder;);
a=0;//     iget-object v3, p0, Lcom/kingroot/RushRoot/ew;->b:Ljava/lang/String;
a=0;// 
a=0;//     invoke-virtual {v0, v3}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     invoke-virtual {v0}, Ljava/lang/StringBuilder;->toString()Ljava/lang/String;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     invoke-static {v0}, Lcom/kingroot/RushRoot/fe;->a(Ljava/lang/String;)V
a=0;// 
a=0;//     .line 106
a=0;//     if-nez v1, :cond_1
a=0;// 
a=0;//     .line 107
a=0;//     iget-object v0, p0, Lcom/kingroot/RushRoot/ew;->a:Lcom/kingroot/RushRoot/et;
a=0;// 
a=0;//     invoke-static {v0}, Lcom/kingroot/RushRoot/et;->b(Lcom/kingroot/RushRoot/et;)Landroid/os/Handler;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     const/4 v3, 0x1
a=0;// 
a=0;//     .line 108
a=0;//     #v3=(One);
a=0;//     const-string v4, "KDShell is null"
a=0;// 
a=0;//     .line 107
a=0;//     #v4=(Reference,Ljava/lang/String;);
a=0;//     invoke-virtual {v0, v3, v4}, Landroid/os/Handler;->obtainMessage(ILjava/lang/Object;)Landroid/os/Message;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     .line 108
a=0;//     invoke-virtual {v0}, Landroid/os/Message;->sendToTarget()V
a=0;// 
a=0;//     .line 109
a=0;//     new-instance v0, Ljava/lang/Exception;
a=0;// 
a=0;//     #v0=(UninitRef,Ljava/lang/Exception;);
a=0;//     const-string v3, "getKDShell failed"
a=0;// 
a=0;//     #v3=(Reference,Ljava/lang/String;);
a=0;//     invoke-direct {v0, v3}, Ljava/lang/Exception;-><init>(Ljava/lang/String;)V
a=0;// 
a=0;//     #v0=(Reference,Ljava/lang/Exception;);
a=0;//     throw v0
a=0;//     :try_end_1
a=0;//     .catchall {:try_start_1 .. :try_end_1} :catchall_0
a=0;// 
a=0;//     .line 103
a=0;//     :catchall_0
a=0;//     #v0=(Conflicted);v3=(Conflicted);v4=(Conflicted);
a=0;//     move-exception v0
a=0;// 
a=0;//     :try_start_2
a=0;//     #v0=(Reference,Ljava/lang/Throwable;);
a=0;//     monitor-exit v2
a=0;// 
a=0;//     throw v0
a=0;//     :try_end_2
a=0;//     .catch Ljava/lang/Exception; {:try_start_2 .. :try_end_2} :catch_0
a=0;// 
a=0;//     .line 163
a=0;//     :catch_0
a=0;//     #v0=(Conflicted);v2=(Conflicted);
a=0;//     move-exception v0
a=0;// 
a=0;//     .line 164
a=0;//     #v0=(Reference,Ljava/lang/Exception;);
a=0;//     iget-object v2, p0, Lcom/kingroot/RushRoot/ew;->a:Lcom/kingroot/RushRoot/et;
a=0;// 
a=0;//     #v2=(Reference,Lcom/kingroot/RushRoot/et;);
a=0;//     invoke-static {v2}, Lcom/kingroot/RushRoot/et;->d(Lcom/kingroot/RushRoot/et;)V
a=0;// 
a=0;//     .line 165
a=0;//     iget-object v2, p0, Lcom/kingroot/RushRoot/ew;->a:Lcom/kingroot/RushRoot/et;
a=0;// 
a=0;//     invoke-static {v2}, Lcom/kingroot/RushRoot/et;->b(Lcom/kingroot/RushRoot/et;)Landroid/os/Handler;
a=0;// 
a=0;//     move-result-object v2
a=0;// 
a=0;//     .line 166
a=0;//     invoke-virtual {v0}, Ljava/lang/Exception;->getMessage()Ljava/lang/String;
a=0;// 
a=0;//     move-result-object v3
a=0;// 
a=0;//     .line 165
a=0;//     #v3=(Reference,Ljava/lang/String;);
a=0;//     invoke-virtual {v2, v5, v3}, Landroid/os/Handler;->obtainMessage(ILjava/lang/Object;)Landroid/os/Message;
a=0;// 
a=0;//     move-result-object v2
a=0;// 
a=0;//     .line 166
a=0;//     invoke-virtual {v2}, Landroid/os/Message;->sendToTarget()V
a=0;// 
a=0;//     .line 167
a=0;//     new-instance v2, Ljava/lang/StringBuilder;
a=0;// 
a=0;//     #v2=(UninitRef,Ljava/lang/StringBuilder;);
a=0;//     const-string v3, "Exception: "
a=0;// 
a=0;//     invoke-direct {v2, v3}, Ljava/lang/StringBuilder;-><init>(Ljava/lang/String;)V
a=0;// 
a=0;//     #v2=(Reference,Ljava/lang/StringBuilder;);
a=0;//     invoke-virtual {v0}, Ljava/lang/Exception;->getMessage()Ljava/lang/String;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     invoke-virtual {v2, v0}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     invoke-virtual {v0}, Ljava/lang/StringBuilder;->toString()Ljava/lang/String;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     invoke-static {v0}, Lcom/kingroot/RushRoot/fe;->b(Ljava/lang/String;)V
a=0;// 
a=0;//     .line 170
a=0;//     :goto_0
a=0;//     #v3=(Conflicted);
a=0;//     iget-object v0, p0, Lcom/kingroot/RushRoot/ew;->a:Lcom/kingroot/RushRoot/et;
a=0;// 
a=0;//     invoke-static {v0}, Lcom/kingroot/RushRoot/et;->d(Lcom/kingroot/RushRoot/et;)V
a=0;// 
a=0;//     .line 172
a=0;//     if-eqz v1, :cond_0
a=0;// 
a=0;//     .line 173
a=0;//     const-string v0, "Close kd"
a=0;// 
a=0;//     invoke-static {v0}, Lcom/kingroot/RushRoot/fe;->a(Ljava/lang/String;)V
a=0;// 
a=0;//     .line 174
a=0;//     invoke-virtual {v1}, Lcom/kingroot/sdk/root/l;->c()V
a=0;// 
a=0;//     .line 175
a=0;//     const-string v0, "Kd closed"
a=0;// 
a=0;//     invoke-static {v0}, Lcom/kingroot/RushRoot/fe;->a(Ljava/lang/String;)V
a=0;// 
a=0;//     .line 178
a=0;//     :cond_0
a=0;//     const-string v0, "SCAN_LOCK released"
a=0;// 
a=0;//     invoke-static {v0}, Lcom/kingroot/RushRoot/fe;->a(Ljava/lang/String;)V
a=0;// 
a=0;//     .line 179
a=0;//     :goto_1
a=0;//     return-void
a=0;// 
a=0;//     .line 112
a=0;//     :cond_1
a=0;//     :try_start_3
a=0;//     #v3=(Reference,Ljava/lang/String;);v4=(Uninit);
a=0;//     iget-object v0, p0, Lcom/kingroot/RushRoot/ew;->a:Lcom/kingroot/RushRoot/et;
a=0;// 
a=0;//     invoke-static {v1}, Lcom/kingroot/RushRoot/et;->a(Lkrsdk/h;)V
a=0;// 
a=0;//     .line 114
a=0;//     new-instance v0, Ljava/lang/StringBuilder;
a=0;// 
a=0;//     .line 115
a=0;//     #v0=(UninitRef,Ljava/lang/StringBuilder;);
a=0;//     invoke-static {}, Lcom/kingroot/RushRoot/fc;->a()Ljava/lang/String;
a=0;// 
a=0;//     move-result-object v3
a=0;// 
a=0;//     invoke-static {v3}, Ljava/lang/String;->valueOf(Ljava/lang/Object;)Ljava/lang/String;
a=0;// 
a=0;//     move-result-object v3
a=0;// 
a=0;//     invoke-direct {v0, v3}, Ljava/lang/StringBuilder;-><init>(Ljava/lang/String;)V
a=0;// 
a=0;//     .line 116
a=0;//     #v0=(Reference,Ljava/lang/StringBuilder;);
a=0;//     const-string v3, " "
a=0;// 
a=0;//     invoke-virtual {v0, v3}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     .line 117
a=0;//     iget-object v3, p0, Lcom/kingroot/RushRoot/ew;->b:Ljava/lang/String;
a=0;// 
a=0;//     invoke-virtual {v0, v3}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     .line 118
a=0;//     const-string v3, " "
a=0;// 
a=0;//     invoke-virtual {v0, v3}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     .line 119
a=0;//     iget-object v3, p0, Lcom/kingroot/RushRoot/ew;->a:Lcom/kingroot/RushRoot/et;
a=0;// 
a=0;//     invoke-virtual {v3}, Lcom/kingroot/RushRoot/et;->d()I
a=0;// 
a=0;//     move-result v3
a=0;// 
a=0;//     #v3=(Integer);
a=0;//     invoke-virtual {v0, v3}, Ljava/lang/StringBuilder;->append(I)Ljava/lang/StringBuilder;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     invoke-virtual {v0}, Ljava/lang/StringBuilder;->toString()Ljava/lang/String;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     .line 114
a=0;//     invoke-virtual {v1, v0}, Lcom/kingroot/sdk/root/l;->a(Ljava/lang/String;)Lkrsdk/i;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     .line 121
a=0;//     iget-object v3, p0, Lcom/kingroot/RushRoot/ew;->a:Lcom/kingroot/RushRoot/et;
a=0;// 
a=0;//     #v3=(Reference,Lcom/kingroot/RushRoot/et;);
a=0;//     invoke-static {v3}, Lcom/kingroot/RushRoot/et;->c(Lcom/kingroot/RushRoot/et;)Z
a=0;// 
a=0;//     move-result v3
a=0;// 
a=0;//     #v3=(Boolean);
a=0;//     if-nez v3, :cond_2
a=0;// 
a=0;//     .line 122
a=0;//     const-string v0, "Close kd"
a=0;// 
a=0;//     invoke-static {v0}, Lcom/kingroot/RushRoot/fe;->a(Ljava/lang/String;)V
a=0;// 
a=0;//     .line 123
a=0;//     invoke-virtual {v1}, Lcom/kingroot/sdk/root/l;->c()V
a=0;// 
a=0;//     .line 124
a=0;//     const-string v0, "Kd closed"
a=0;// 
a=0;//     invoke-static {v0}, Lcom/kingroot/RushRoot/fe;->a(Ljava/lang/String;)V
a=0;// 
a=0;//     .line 125
a=0;//     const-string v0, "SCAN_LOCK released"
a=0;// 
a=0;//     invoke-static {v0}, Lcom/kingroot/RushRoot/fe;->a(Ljava/lang/String;)V
a=0;// 
a=0;//     .line 126
a=0;//     monitor-exit v2
a=0;// 
a=0;//     goto :goto_1
a=0;// 
a=0;//     .line 129
a=0;//     :cond_2
a=0;//     new-instance v3, Ljava/lang/StringBuilder;
a=0;// 
a=0;//     #v3=(UninitRef,Ljava/lang/StringBuilder;);
a=0;//     const-string v4, "Scan "
a=0;// 
a=0;//     #v4=(Reference,Ljava/lang/String;);
a=0;//     invoke-direct {v3, v4}, Ljava/lang/StringBuilder;-><init>(Ljava/lang/String;)V
a=0;// 
a=0;//     #v3=(Reference,Ljava/lang/StringBuilder;);
a=0;//     iget-object v4, p0, Lcom/kingroot/RushRoot/ew;->a:Lcom/kingroot/RushRoot/et;
a=0;// 
a=0;//     invoke-virtual {v4}, Lcom/kingroot/RushRoot/et;->c()Ljava/lang/String;
a=0;// 
a=0;//     move-result-object v4
a=0;// 
a=0;//     invoke-virtual {v3, v4}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;
a=0;// 
a=0;//     move-result-object v3
a=0;// 
a=0;//     const-string v4, " finished"
a=0;// 
a=0;//     invoke-virtual {v3, v4}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;
a=0;// 
a=0;//     move-result-object v3
a=0;// 
a=0;//     invoke-virtual {v3}, Ljava/lang/StringBuilder;->toString()Ljava/lang/String;
a=0;// 
a=0;//     move-result-object v3
a=0;// 
a=0;//     invoke-static {v3}, Lcom/kingroot/RushRoot/fe;->a(Ljava/lang/String;)V
a=0;// 
a=0;//     .line 152
a=0;//     iget-object v3, p0, Lcom/kingroot/RushRoot/ew;->a:Lcom/kingroot/RushRoot/et;
a=0;// 
a=0;//     invoke-static {v3}, Lcom/kingroot/RushRoot/et;->d(Lcom/kingroot/RushRoot/et;)V
a=0;// 
a=0;//     .line 153
a=0;//     if-eqz v0, :cond_3
a=0;// 
a=0;//     invoke-virtual {v0}, Lkrsdk/i;->a()Z
a=0;// 
a=0;//     move-result v3
a=0;// 
a=0;//     #v3=(Boolean);
a=0;//     if-eqz v3, :cond_3
a=0;// 
a=0;//     .line 154
a=0;//     iget-object v3, v0, Lkrsdk/i;->b:Ljava/lang/String;
a=0;// 
a=0;//     #v3=(Reference,Ljava/lang/String;);
a=0;//     if-nez v3, :cond_4
a=0;// 
a=0;//     .line 155
a=0;//     :cond_3
a=0;//     #v3=(Conflicted);
a=0;//     iget-object v0, p0, Lcom/kingroot/RushRoot/ew;->a:Lcom/kingroot/RushRoot/et;
a=0;// 
a=0;//     invoke-static {v0}, Lcom/kingroot/RushRoot/et;->b(Lcom/kingroot/RushRoot/et;)Landroid/os/Handler;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     const/4 v3, 0x1
a=0;// 
a=0;//     .line 156
a=0;//     #v3=(One);
a=0;//     const-string v4, "scanner failed"
a=0;// 
a=0;//     .line 155
a=0;//     invoke-virtual {v0, v3, v4}, Landroid/os/Handler;->obtainMessage(ILjava/lang/Object;)Landroid/os/Message;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     .line 156
a=0;//     invoke-virtual {v0}, Landroid/os/Message;->sendToTarget()V
a=0;// 
a=0;//     .line 103
a=0;//     :goto_2
a=0;//     #v3=(Conflicted);
a=0;//     monitor-exit v2
a=0;// 
a=0;//     goto/16 :goto_0
a=0;// 
a=0;//     .line 158
a=0;//     :cond_4
a=0;//     #v3=(Reference,Ljava/lang/String;);
a=0;//     iget-object v3, p0, Lcom/kingroot/RushRoot/ew;->a:Lcom/kingroot/RushRoot/et;
a=0;// 
a=0;//     invoke-static {v3}, Lcom/kingroot/RushRoot/et;->b(Lcom/kingroot/RushRoot/et;)Landroid/os/Handler;
a=0;// 
a=0;//     move-result-object v3
a=0;// 
a=0;//     .line 159
a=0;//     const/4 v4, 0x0
a=0;// 
a=0;//     #v4=(Null);
a=0;//     iget-object v0, v0, Lkrsdk/i;->b:Ljava/lang/String;
a=0;// 
a=0;//     .line 158
a=0;//     invoke-virtual {v3, v4, v0}, Landroid/os/Handler;->obtainMessage(ILjava/lang/Object;)Landroid/os/Message;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     .line 160
a=0;//     invoke-virtual {v0}, Landroid/os/Message;->sendToTarget()V
a=0;//     :try_end_3
a=0;//     .catchall {:try_start_3 .. :try_end_3} :catchall_0
a=0;// 
a=0;//     goto :goto_2
a=0;// .end method
}}
