package com.kingroot.RushRoot; class fo { void a() { int a;
a=0;// .class public final Lcom/kingroot/RushRoot/fo;
a=0;// .super Ljava/lang/Thread;
a=0;// .source "SourceFile"
a=0;// 
a=0;// 
a=0;// # instance fields
a=0;// .field a:Ljava/io/InputStream;
a=0;// 
a=0;// .field b:Ljava/io/ByteArrayOutputStream;
a=0;// 
a=0;// .field final synthetic c:Lcom/kingroot/RushRoot/fn;
a=0;// 
a=0;// 
a=0;// # direct methods
a=0;// .method public constructor <init>(Lcom/kingroot/RushRoot/fn;Ljava/lang/String;Ljava/io/InputStream;Ljava/io/ByteArrayOutputStream;)V
a=0;//     .locals 0
a=0;// 
a=0;//     .prologue
a=0;//     .line 427
a=0;//     iput-object p1, p0, Lcom/kingroot/RushRoot/fo;->c:Lcom/kingroot/RushRoot/fn;
a=0;// 
a=0;//     .line 428
a=0;//     invoke-direct {p0, p2}, Ljava/lang/Thread;-><init>(Ljava/lang/String;)V
a=0;// 
a=0;//     .line 429
a=0;//     #p0=(Reference,Lcom/kingroot/RushRoot/fo;);
a=0;//     iput-object p3, p0, Lcom/kingroot/RushRoot/fo;->a:Ljava/io/InputStream;
a=0;// 
a=0;//     .line 430
a=0;//     iput-object p4, p0, Lcom/kingroot/RushRoot/fo;->b:Ljava/io/ByteArrayOutputStream;
a=0;// 
a=0;//     .line 431
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// 
a=0;// # virtual methods
a=0;// .method public final run()V
a=0;//     .locals 5
a=0;// 
a=0;//     .prologue
a=0;//     .line 436
a=0;//     const/16 v0, 0x400
a=0;// 
a=0;//     :try_start_0
a=0;//     #v0=(PosShort);
a=0;//     new-array v0, v0, [B
a=0;// 
a=0;//     .line 438
a=0;//     :cond_0
a=0;//     :goto_0
a=0;//     #v0=(Reference,[B);v1=(Conflicted);v2=(Conflicted);v3=(Conflicted);v4=(Conflicted);
a=0;//     iget-object v1, p0, Lcom/kingroot/RushRoot/fo;->a:Ljava/io/InputStream;
a=0;// 
a=0;//     #v1=(Reference,Ljava/io/InputStream;);
a=0;//     invoke-virtual {v1, v0}, Ljava/io/InputStream;->read([B)I
a=0;// 
a=0;//     move-result v1
a=0;// 
a=0;//     .line 439
a=0;//     #v1=(Integer);
a=0;//     if-gez v1, :cond_1
a=0;// 
a=0;//     .line 440
a=0;//     iget-object v0, p0, Lcom/kingroot/RushRoot/fo;->c:Lcom/kingroot/RushRoot/fn;
a=0;// 
a=0;//     invoke-static {v0}, Lcom/kingroot/RushRoot/fn;->a(Lcom/kingroot/RushRoot/fn;)Ljava/lang/Object;
a=0;// 
a=0;//     move-result-object v1
a=0;// 
a=0;//     #v1=(Reference,Ljava/lang/Object;);
a=0;//     monitor-enter v1
a=0;//     :try_end_0
a=0;//     .catch Ljava/lang/Exception; {:try_start_0 .. :try_end_0} :catch_0
a=0;// 
a=0;//     .line 441
a=0;//     :try_start_1
a=0;//     const-string v0, ":RET=EOF"
a=0;// 
a=0;//     invoke-virtual {v0}, Ljava/lang/String;->getBytes()[B
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     .line 442
a=0;//     iget-object v2, p0, Lcom/kingroot/RushRoot/fo;->b:Ljava/io/ByteArrayOutputStream;
a=0;// 
a=0;//     #v2=(Reference,Ljava/io/ByteArrayOutputStream;);
a=0;//     invoke-virtual {v2, v0}, Ljava/io/ByteArrayOutputStream;->write([B)V
a=0;// 
a=0;//     .line 443
a=0;//     iget-object v0, p0, Lcom/kingroot/RushRoot/fo;->b:Ljava/io/ByteArrayOutputStream;
a=0;// 
a=0;//     invoke-virtual {v0}, Ljava/io/ByteArrayOutputStream;->flush()V
a=0;// 
a=0;//     .line 440
a=0;//     monitor-exit v1
a=0;//     :try_end_1
a=0;//     .catchall {:try_start_1 .. :try_end_1} :catchall_0
a=0;// 
a=0;//     .line 445
a=0;//     :try_start_2
a=0;//     iget-object v0, p0, Lcom/kingroot/RushRoot/fo;->c:Lcom/kingroot/RushRoot/fn;
a=0;// 
a=0;//     invoke-static {v0}, Lcom/kingroot/RushRoot/fn;->b(Lcom/kingroot/RushRoot/fn;)Ljava/lang/Object;
a=0;// 
a=0;//     move-result-object v1
a=0;// 
a=0;//     monitor-enter v1
a=0;//     :try_end_2
a=0;//     .catch Ljava/lang/Exception; {:try_start_2 .. :try_end_2} :catch_0
a=0;// 
a=0;//     .line 446
a=0;//     :try_start_3
a=0;//     iget-object v0, p0, Lcom/kingroot/RushRoot/fo;->c:Lcom/kingroot/RushRoot/fn;
a=0;// 
a=0;//     invoke-static {v0}, Lcom/kingroot/RushRoot/fn;->b(Lcom/kingroot/RushRoot/fn;)Ljava/lang/Object;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     invoke-virtual {v0}, Ljava/lang/Object;->notifyAll()V
a=0;// 
a=0;//     .line 445
a=0;//     monitor-exit v1
a=0;//     :try_end_3
a=0;//     .catchall {:try_start_3 .. :try_end_3} :catchall_1
a=0;// 
a=0;//     .line 463
a=0;//     :goto_1
a=0;//     #v1=(Conflicted);v2=(Conflicted);
a=0;//     return-void
a=0;// 
a=0;//     .line 440
a=0;//     :catchall_0
a=0;//     #v1=(Reference,Ljava/lang/Object;);
a=0;//     move-exception v0
a=0;// 
a=0;//     :try_start_4
a=0;//     monitor-exit v1
a=0;// 
a=0;//     throw v0
a=0;// 
a=0;//     .line 463
a=0;//     :catch_0
a=0;//     #v0=(Conflicted);v1=(Conflicted);
a=0;//     move-exception v0
a=0;// 
a=0;//     #v0=(Reference,Ljava/lang/Exception;);
a=0;//     goto :goto_1
a=0;// 
a=0;//     .line 445
a=0;//     :catchall_1
a=0;//     #v1=(Reference,Ljava/lang/Object;);v2=(Reference,Ljava/io/ByteArrayOutputStream;);
a=0;//     move-exception v0
a=0;// 
a=0;//     monitor-exit v1
a=0;// 
a=0;//     throw v0
a=0;// 
a=0;//     .line 448
a=0;//     :cond_1
a=0;//     #v1=(Integer);v2=(Conflicted);
a=0;//     if-lez v1, :cond_0
a=0;// 
a=0;//     .line 451
a=0;//     iget-object v2, p0, Lcom/kingroot/RushRoot/fo;->c:Lcom/kingroot/RushRoot/fn;
a=0;// 
a=0;//     #v2=(Reference,Lcom/kingroot/RushRoot/fn;);
a=0;//     invoke-static {v2}, Lcom/kingroot/RushRoot/fn;->a(Lcom/kingroot/RushRoot/fn;)Ljava/lang/Object;
a=0;// 
a=0;//     move-result-object v2
a=0;// 
a=0;//     monitor-enter v2
a=0;//     :try_end_4
a=0;//     .catch Ljava/lang/Exception; {:try_start_4 .. :try_end_4} :catch_0
a=0;// 
a=0;//     .line 452
a=0;//     :try_start_5
a=0;//     iget-object v3, p0, Lcom/kingroot/RushRoot/fo;->b:Ljava/io/ByteArrayOutputStream;
a=0;// 
a=0;//     #v3=(Reference,Ljava/io/ByteArrayOutputStream;);
a=0;//     const/4 v4, 0x0
a=0;// 
a=0;//     #v4=(Null);
a=0;//     invoke-virtual {v3, v0, v4, v1}, Ljava/io/ByteArrayOutputStream;->write([BII)V
a=0;// 
a=0;//     .line 453
a=0;//     iget-object v1, p0, Lcom/kingroot/RushRoot/fo;->b:Ljava/io/ByteArrayOutputStream;
a=0;// 
a=0;//     #v1=(Reference,Ljava/io/ByteArrayOutputStream;);
a=0;//     invoke-virtual {v1}, Ljava/io/ByteArrayOutputStream;->flush()V
a=0;// 
a=0;//     .line 451
a=0;//     monitor-exit v2
a=0;//     :try_end_5
a=0;//     .catchall {:try_start_5 .. :try_end_5} :catchall_3
a=0;// 
a=0;//     .line 455
a=0;//     :try_start_6
a=0;//     iget-object v1, p0, Lcom/kingroot/RushRoot/fo;->c:Lcom/kingroot/RushRoot/fn;
a=0;// 
a=0;//     invoke-static {v1}, Lcom/kingroot/RushRoot/fn;->b(Lcom/kingroot/RushRoot/fn;)Ljava/lang/Object;
a=0;// 
a=0;//     move-result-object v1
a=0;// 
a=0;//     monitor-enter v1
a=0;//     :try_end_6
a=0;//     .catch Ljava/lang/Exception; {:try_start_6 .. :try_end_6} :catch_0
a=0;// 
a=0;//     .line 456
a=0;//     :try_start_7
a=0;//     iget-object v2, p0, Lcom/kingroot/RushRoot/fo;->c:Lcom/kingroot/RushRoot/fn;
a=0;// 
a=0;//     invoke-static {v2}, Lcom/kingroot/RushRoot/fn;->b(Lcom/kingroot/RushRoot/fn;)Ljava/lang/Object;
a=0;// 
a=0;//     move-result-object v2
a=0;// 
a=0;//     invoke-virtual {v2}, Ljava/lang/Object;->notifyAll()V
a=0;// 
a=0;//     .line 455
a=0;//     monitor-exit v1
a=0;//     :try_end_7
a=0;//     .catchall {:try_start_7 .. :try_end_7} :catchall_2
a=0;// 
a=0;//     goto :goto_0
a=0;// 
a=0;//     :catchall_2
a=0;//     move-exception v0
a=0;// 
a=0;//     :try_start_8
a=0;//     monitor-exit v1
a=0;// 
a=0;//     throw v0
a=0;// 
a=0;//     .line 451
a=0;//     :catchall_3
a=0;//     #v1=(Conflicted);v3=(Conflicted);v4=(Conflicted);
a=0;//     move-exception v0
a=0;// 
a=0;//     monitor-exit v2
a=0;// 
a=0;//     throw v0
a=0;//     :try_end_8
a=0;//     .catch Ljava/lang/Exception; {:try_start_8 .. :try_end_8} :catch_0
a=0;// .end method
}}
