package com.kingroot.RushRoot; class g { void a() { int a;
a=0;// .class public abstract Lcom/kingroot/RushRoot/g;
a=0;// .super Ljava/lang/Object;
a=0;// .source "SourceFile"
a=0;// 
a=0;// # interfaces
a=0;// .implements Ljava/lang/Cloneable;
a=0;// 
a=0;// 
a=0;// # instance fields
a=0;// .field a:F
a=0;// 
a=0;// .field b:Ljava/lang/Class;
a=0;// 
a=0;// .field c:Z
a=0;// 
a=0;// .field private d:Lcom/kingroot/RushRoot/l;
a=0;// 
a=0;// 
a=0;// # direct methods
a=0;// .method public constructor <init>()V
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 41
a=0;//     invoke-direct {p0}, Ljava/lang/Object;-><init>()V
a=0;// 
a=0;//     .line 59
a=0;//     #p0=(Reference,Lcom/kingroot/RushRoot/g;);
a=0;//     const/4 v0, 0x0
a=0;// 
a=0;//     #v0=(Null);
a=0;//     iput-object v0, p0, Lcom/kingroot/RushRoot/g;->d:Lcom/kingroot/RushRoot/l;
a=0;// 
a=0;//     .line 66
a=0;//     const/4 v0, 0x0
a=0;// 
a=0;//     iput-boolean v0, p0, Lcom/kingroot/RushRoot/g;->c:Z
a=0;// 
a=0;//     .line 356
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public static a(FLjava/lang/Object;)Lcom/kingroot/RushRoot/g;
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 163
a=0;//     new-instance v0, Lcom/kingroot/RushRoot/h;
a=0;// 
a=0;//     #v0=(UninitRef,Lcom/kingroot/RushRoot/h;);
a=0;//     invoke-direct {v0, p0, p1}, Lcom/kingroot/RushRoot/h;-><init>(FLjava/lang/Object;)V
a=0;// 
a=0;//     #v0=(Reference,Lcom/kingroot/RushRoot/h;);
a=0;//     return-object v0
a=0;// .end method
a=0;// 
a=0;// 
a=0;// # virtual methods
a=0;// .method public abstract a()Ljava/lang/Object;
a=0;// .end method
a=0;// 
a=0;// .method public final a(Lcom/kingroot/RushRoot/l;)V
a=0;//     .locals 0
a=0;// 
a=0;//     .prologue
a=0;//     .line 256
a=0;//     iput-object p1, p0, Lcom/kingroot/RushRoot/g;->d:Lcom/kingroot/RushRoot/l;
a=0;// 
a=0;//     .line 257
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public abstract a(Ljava/lang/Object;)V
a=0;// .end method
a=0;// 
a=0;// .method public final b()Lcom/kingroot/RushRoot/l;
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 245
a=0;//     iget-object v0, p0, Lcom/kingroot/RushRoot/g;->d:Lcom/kingroot/RushRoot/l;
a=0;// 
a=0;//     #v0=(Reference,Lcom/kingroot/RushRoot/l;);
a=0;//     return-object v0
a=0;// .end method
a=0;// 
a=0;// .method public abstract c()Lcom/kingroot/RushRoot/g;
a=0;// .end method
a=0;// 
a=0;// .method public synthetic clone()Ljava/lang/Object;
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 41
a=0;//     invoke-virtual {p0}, Lcom/kingroot/RushRoot/g;->c()Lcom/kingroot/RushRoot/g;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     #v0=(Reference,Lcom/kingroot/RushRoot/g;);
a=0;//     return-object v0
a=0;// .end method
}}
