package com.kingroot.RushRoot; class gk { void a() { int a;
a=0;// .class public final Lcom/kingroot/RushRoot/gk;
a=0;// .super Lcom/kingroot/RushRoot/hi;
a=0;// .source "SourceFile"
a=0;// 
a=0;// 
a=0;// # instance fields
a=0;// .field public a:Ljava/lang/String;
a=0;// 
a=0;// .field public b:Ljava/lang/String;
a=0;// 
a=0;// .field public c:Ljava/lang/String;
a=0;// 
a=0;// .field public d:Ljava/lang/String;
a=0;// 
a=0;// .field public e:Ljava/lang/String;
a=0;// 
a=0;// .field public f:I
a=0;// 
a=0;// .field public g:Ljava/lang/String;
a=0;// 
a=0;// .field public h:Ljava/lang/String;
a=0;// 
a=0;// .field public i:Ljava/lang/String;
a=0;// 
a=0;// .field public j:Ljava/lang/String;
a=0;// 
a=0;// 
a=0;// # direct methods
a=0;// .method public constructor <init>()V
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 21
a=0;//     invoke-direct {p0}, Lcom/kingroot/RushRoot/hi;-><init>()V
a=0;// 
a=0;//     .line 10
a=0;//     #p0=(Reference,Lcom/kingroot/RushRoot/gk;);
a=0;//     const-string v0, ""
a=0;// 
a=0;//     #v0=(Reference,Ljava/lang/String;);
a=0;//     iput-object v0, p0, Lcom/kingroot/RushRoot/gk;->a:Ljava/lang/String;
a=0;// 
a=0;//     .line 11
a=0;//     const-string v0, ""
a=0;// 
a=0;//     iput-object v0, p0, Lcom/kingroot/RushRoot/gk;->b:Ljava/lang/String;
a=0;// 
a=0;//     .line 12
a=0;//     const-string v0, ""
a=0;// 
a=0;//     iput-object v0, p0, Lcom/kingroot/RushRoot/gk;->c:Ljava/lang/String;
a=0;// 
a=0;//     .line 13
a=0;//     const-string v0, ""
a=0;// 
a=0;//     iput-object v0, p0, Lcom/kingroot/RushRoot/gk;->d:Ljava/lang/String;
a=0;// 
a=0;//     .line 14
a=0;//     const-string v0, ""
a=0;// 
a=0;//     iput-object v0, p0, Lcom/kingroot/RushRoot/gk;->e:Ljava/lang/String;
a=0;// 
a=0;//     .line 15
a=0;//     const/4 v0, 0x0
a=0;// 
a=0;//     #v0=(Null);
a=0;//     iput v0, p0, Lcom/kingroot/RushRoot/gk;->f:I
a=0;// 
a=0;//     .line 16
a=0;//     const-string v0, ""
a=0;// 
a=0;//     #v0=(Reference,Ljava/lang/String;);
a=0;//     iput-object v0, p0, Lcom/kingroot/RushRoot/gk;->g:Ljava/lang/String;
a=0;// 
a=0;//     .line 17
a=0;//     const-string v0, ""
a=0;// 
a=0;//     iput-object v0, p0, Lcom/kingroot/RushRoot/gk;->h:Ljava/lang/String;
a=0;// 
a=0;//     .line 18
a=0;//     const-string v0, ""
a=0;// 
a=0;//     iput-object v0, p0, Lcom/kingroot/RushRoot/gk;->i:Ljava/lang/String;
a=0;// 
a=0;//     .line 19
a=0;//     const-string v0, ""
a=0;// 
a=0;//     iput-object v0, p0, Lcom/kingroot/RushRoot/gk;->j:Ljava/lang/String;
a=0;// 
a=0;//     .line 22
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// 
a=0;// # virtual methods
a=0;// .method public final a(Lcom/kingroot/RushRoot/hf;)V
a=0;//     .locals 3
a=0;// 
a=0;//     .prologue
a=0;//     const/4 v1, 0x1
a=0;// 
a=0;//     #v1=(One);
a=0;//     const/4 v2, 0x0
a=0;// 
a=0;//     .line 57
a=0;//     #v2=(Null);
a=0;//     invoke-virtual {p1, v2, v1}, Lcom/kingroot/RushRoot/hf;->a(IZ)Ljava/lang/String;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     #v0=(Reference,Ljava/lang/String;);
a=0;//     iput-object v0, p0, Lcom/kingroot/RushRoot/gk;->a:Ljava/lang/String;
a=0;// 
a=0;//     .line 58
a=0;//     invoke-virtual {p1, v1, v2}, Lcom/kingroot/RushRoot/hf;->a(IZ)Ljava/lang/String;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     iput-object v0, p0, Lcom/kingroot/RushRoot/gk;->b:Ljava/lang/String;
a=0;// 
a=0;//     .line 59
a=0;//     const/4 v0, 0x2
a=0;// 
a=0;//     #v0=(PosByte);
a=0;//     invoke-virtual {p1, v0, v2}, Lcom/kingroot/RushRoot/hf;->a(IZ)Ljava/lang/String;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     #v0=(Reference,Ljava/lang/String;);
a=0;//     iput-object v0, p0, Lcom/kingroot/RushRoot/gk;->c:Ljava/lang/String;
a=0;// 
a=0;//     .line 60
a=0;//     const/4 v0, 0x3
a=0;// 
a=0;//     #v0=(PosByte);
a=0;//     invoke-virtual {p1, v0, v2}, Lcom/kingroot/RushRoot/hf;->a(IZ)Ljava/lang/String;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     #v0=(Reference,Ljava/lang/String;);
a=0;//     iput-object v0, p0, Lcom/kingroot/RushRoot/gk;->d:Ljava/lang/String;
a=0;// 
a=0;//     .line 61
a=0;//     const/4 v0, 0x4
a=0;// 
a=0;//     #v0=(PosByte);
a=0;//     invoke-virtual {p1, v0, v2}, Lcom/kingroot/RushRoot/hf;->a(IZ)Ljava/lang/String;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     #v0=(Reference,Ljava/lang/String;);
a=0;//     iput-object v0, p0, Lcom/kingroot/RushRoot/gk;->e:Ljava/lang/String;
a=0;// 
a=0;//     .line 62
a=0;//     iget v0, p0, Lcom/kingroot/RushRoot/gk;->f:I
a=0;// 
a=0;//     #v0=(Integer);
a=0;//     const/4 v1, 0x5
a=0;// 
a=0;//     #v1=(PosByte);
a=0;//     invoke-virtual {p1, v0, v1, v2}, Lcom/kingroot/RushRoot/hf;->a(IIZ)I
a=0;// 
a=0;//     move-result v0
a=0;// 
a=0;//     iput v0, p0, Lcom/kingroot/RushRoot/gk;->f:I
a=0;// 
a=0;//     .line 63
a=0;//     const/4 v0, 0x6
a=0;// 
a=0;//     #v0=(PosByte);
a=0;//     invoke-virtual {p1, v0, v2}, Lcom/kingroot/RushRoot/hf;->a(IZ)Ljava/lang/String;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     #v0=(Reference,Ljava/lang/String;);
a=0;//     iput-object v0, p0, Lcom/kingroot/RushRoot/gk;->g:Ljava/lang/String;
a=0;// 
a=0;//     .line 64
a=0;//     const/4 v0, 0x7
a=0;// 
a=0;//     #v0=(PosByte);
a=0;//     invoke-virtual {p1, v0, v2}, Lcom/kingroot/RushRoot/hf;->a(IZ)Ljava/lang/String;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     #v0=(Reference,Ljava/lang/String;);
a=0;//     iput-object v0, p0, Lcom/kingroot/RushRoot/gk;->h:Ljava/lang/String;
a=0;// 
a=0;//     .line 65
a=0;//     const/16 v0, 0x8
a=0;// 
a=0;//     #v0=(PosByte);
a=0;//     invoke-virtual {p1, v0, v2}, Lcom/kingroot/RushRoot/hf;->a(IZ)Ljava/lang/String;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     #v0=(Reference,Ljava/lang/String;);
a=0;//     iput-object v0, p0, Lcom/kingroot/RushRoot/gk;->i:Ljava/lang/String;
a=0;// 
a=0;//     .line 66
a=0;//     const/16 v0, 0x9
a=0;// 
a=0;//     #v0=(PosByte);
a=0;//     invoke-virtual {p1, v0, v2}, Lcom/kingroot/RushRoot/hf;->a(IZ)Ljava/lang/String;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     #v0=(Reference,Ljava/lang/String;);
a=0;//     iput-object v0, p0, Lcom/kingroot/RushRoot/gk;->j:Ljava/lang/String;
a=0;// 
a=0;//     .line 67
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public final a(Lcom/kingroot/RushRoot/hh;)V
a=0;//     .locals 2
a=0;// 
a=0;//     .prologue
a=0;//     .line 25
a=0;//     iget-object v0, p0, Lcom/kingroot/RushRoot/gk;->a:Ljava/lang/String;
a=0;// 
a=0;//     #v0=(Reference,Ljava/lang/String;);
a=0;//     const/4 v1, 0x0
a=0;// 
a=0;//     #v1=(Null);
a=0;//     invoke-virtual {p1, v0, v1}, Lcom/kingroot/RushRoot/hh;->a(Ljava/lang/String;I)V
a=0;// 
a=0;//     .line 26
a=0;//     iget-object v0, p0, Lcom/kingroot/RushRoot/gk;->b:Ljava/lang/String;
a=0;// 
a=0;//     if-eqz v0, :cond_0
a=0;// 
a=0;//     .line 27
a=0;//     iget-object v0, p0, Lcom/kingroot/RushRoot/gk;->b:Ljava/lang/String;
a=0;// 
a=0;//     const/4 v1, 0x1
a=0;// 
a=0;//     #v1=(One);
a=0;//     invoke-virtual {p1, v0, v1}, Lcom/kingroot/RushRoot/hh;->a(Ljava/lang/String;I)V
a=0;// 
a=0;//     .line 29
a=0;//     :cond_0
a=0;//     #v1=(Boolean);
a=0;//     iget-object v0, p0, Lcom/kingroot/RushRoot/gk;->c:Ljava/lang/String;
a=0;// 
a=0;//     if-eqz v0, :cond_1
a=0;// 
a=0;//     .line 30
a=0;//     iget-object v0, p0, Lcom/kingroot/RushRoot/gk;->c:Ljava/lang/String;
a=0;// 
a=0;//     const/4 v1, 0x2
a=0;// 
a=0;//     #v1=(PosByte);
a=0;//     invoke-virtual {p1, v0, v1}, Lcom/kingroot/RushRoot/hh;->a(Ljava/lang/String;I)V
a=0;// 
a=0;//     .line 32
a=0;//     :cond_1
a=0;//     iget-object v0, p0, Lcom/kingroot/RushRoot/gk;->d:Ljava/lang/String;
a=0;// 
a=0;//     if-eqz v0, :cond_2
a=0;// 
a=0;//     .line 33
a=0;//     iget-object v0, p0, Lcom/kingroot/RushRoot/gk;->d:Ljava/lang/String;
a=0;// 
a=0;//     const/4 v1, 0x3
a=0;// 
a=0;//     invoke-virtual {p1, v0, v1}, Lcom/kingroot/RushRoot/hh;->a(Ljava/lang/String;I)V
a=0;// 
a=0;//     .line 35
a=0;//     :cond_2
a=0;//     iget-object v0, p0, Lcom/kingroot/RushRoot/gk;->e:Ljava/lang/String;
a=0;// 
a=0;//     if-eqz v0, :cond_3
a=0;// 
a=0;//     .line 36
a=0;//     iget-object v0, p0, Lcom/kingroot/RushRoot/gk;->e:Ljava/lang/String;
a=0;// 
a=0;//     const/4 v1, 0x4
a=0;// 
a=0;//     invoke-virtual {p1, v0, v1}, Lcom/kingroot/RushRoot/hh;->a(Ljava/lang/String;I)V
a=0;// 
a=0;//     .line 38
a=0;//     :cond_3
a=0;//     iget v0, p0, Lcom/kingroot/RushRoot/gk;->f:I
a=0;// 
a=0;//     #v0=(Integer);
a=0;//     if-eqz v0, :cond_4
a=0;// 
a=0;//     .line 39
a=0;//     iget v0, p0, Lcom/kingroot/RushRoot/gk;->f:I
a=0;// 
a=0;//     const/4 v1, 0x5
a=0;// 
a=0;//     invoke-virtual {p1, v0, v1}, Lcom/kingroot/RushRoot/hh;->a(II)V
a=0;// 
a=0;//     .line 41
a=0;//     :cond_4
a=0;//     iget-object v0, p0, Lcom/kingroot/RushRoot/gk;->g:Ljava/lang/String;
a=0;// 
a=0;//     #v0=(Reference,Ljava/lang/String;);
a=0;//     if-eqz v0, :cond_5
a=0;// 
a=0;//     .line 42
a=0;//     iget-object v0, p0, Lcom/kingroot/RushRoot/gk;->g:Ljava/lang/String;
a=0;// 
a=0;//     const/4 v1, 0x6
a=0;// 
a=0;//     invoke-virtual {p1, v0, v1}, Lcom/kingroot/RushRoot/hh;->a(Ljava/lang/String;I)V
a=0;// 
a=0;//     .line 44
a=0;//     :cond_5
a=0;//     iget-object v0, p0, Lcom/kingroot/RushRoot/gk;->h:Ljava/lang/String;
a=0;// 
a=0;//     if-eqz v0, :cond_6
a=0;// 
a=0;//     .line 45
a=0;//     iget-object v0, p0, Lcom/kingroot/RushRoot/gk;->h:Ljava/lang/String;
a=0;// 
a=0;//     const/4 v1, 0x7
a=0;// 
a=0;//     invoke-virtual {p1, v0, v1}, Lcom/kingroot/RushRoot/hh;->a(Ljava/lang/String;I)V
a=0;// 
a=0;//     .line 47
a=0;//     :cond_6
a=0;//     iget-object v0, p0, Lcom/kingroot/RushRoot/gk;->i:Ljava/lang/String;
a=0;// 
a=0;//     if-eqz v0, :cond_7
a=0;// 
a=0;//     .line 48
a=0;//     iget-object v0, p0, Lcom/kingroot/RushRoot/gk;->i:Ljava/lang/String;
a=0;// 
a=0;//     const/16 v1, 0x8
a=0;// 
a=0;//     invoke-virtual {p1, v0, v1}, Lcom/kingroot/RushRoot/hh;->a(Ljava/lang/String;I)V
a=0;// 
a=0;//     .line 50
a=0;//     :cond_7
a=0;//     iget-object v0, p0, Lcom/kingroot/RushRoot/gk;->j:Ljava/lang/String;
a=0;// 
a=0;//     if-eqz v0, :cond_8
a=0;// 
a=0;//     .line 51
a=0;//     iget-object v0, p0, Lcom/kingroot/RushRoot/gk;->j:Ljava/lang/String;
a=0;// 
a=0;//     const/16 v1, 0x9
a=0;// 
a=0;//     invoke-virtual {p1, v0, v1}, Lcom/kingroot/RushRoot/hh;->a(Ljava/lang/String;I)V
a=0;// 
a=0;//     .line 53
a=0;//     :cond_8
a=0;//     return-void
a=0;// .end method
}}
