package com.kingroot.RushRoot; class gs { void a() { int a;
a=0;// .class public final Lcom/kingroot/RushRoot/gs;
a=0;// .super Lcom/kingroot/RushRoot/hi;
a=0;// .source "SourceFile"
a=0;// 
a=0;// 
a=0;// # static fields
a=0;// .field static c:Lcom/kingroot/RushRoot/gr;
a=0;// 
a=0;// .field static d:[B
a=0;// 
a=0;// 
a=0;// # instance fields
a=0;// .field public a:Lcom/kingroot/RushRoot/gr;
a=0;// 
a=0;// .field public b:[B
a=0;// 
a=0;// 
a=0;// # direct methods
a=0;// .method public constructor <init>()V
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     const/4 v0, 0x0
a=0;// 
a=0;//     .line 13
a=0;//     #v0=(Null);
a=0;//     invoke-direct {p0}, Lcom/kingroot/RushRoot/hi;-><init>()V
a=0;// 
a=0;//     .line 10
a=0;//     #p0=(Reference,Lcom/kingroot/RushRoot/gs;);
a=0;//     iput-object v0, p0, Lcom/kingroot/RushRoot/gs;->a:Lcom/kingroot/RushRoot/gr;
a=0;// 
a=0;//     .line 11
a=0;//     iput-object v0, p0, Lcom/kingroot/RushRoot/gs;->b:[B
a=0;// 
a=0;//     .line 14
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// 
a=0;// # virtual methods
a=0;// .method public final a(Lcom/kingroot/RushRoot/hf;)V
a=0;//     .locals 3
a=0;// 
a=0;//     .prologue
a=0;//     const/4 v2, 0x0
a=0;// 
a=0;//     #v2=(Null);
a=0;//     const/4 v1, 0x1
a=0;// 
a=0;//     .line 25
a=0;//     #v1=(One);
a=0;//     sget-object v0, Lcom/kingroot/RushRoot/gs;->c:Lcom/kingroot/RushRoot/gr;
a=0;// 
a=0;//     #v0=(Reference,Lcom/kingroot/RushRoot/gr;);
a=0;//     if-nez v0, :cond_0
a=0;// 
a=0;//     .line 26
a=0;//     new-instance v0, Lcom/kingroot/RushRoot/gr;
a=0;// 
a=0;//     #v0=(UninitRef,Lcom/kingroot/RushRoot/gr;);
a=0;//     invoke-direct {v0}, Lcom/kingroot/RushRoot/gr;-><init>()V
a=0;// 
a=0;//     #v0=(Reference,Lcom/kingroot/RushRoot/gr;);
a=0;//     sput-object v0, Lcom/kingroot/RushRoot/gs;->c:Lcom/kingroot/RushRoot/gr;
a=0;// 
a=0;//     .line 28
a=0;//     :cond_0
a=0;//     sget-object v0, Lcom/kingroot/RushRoot/gs;->c:Lcom/kingroot/RushRoot/gr;
a=0;// 
a=0;//     invoke-virtual {p1, v0, v2, v1}, Lcom/kingroot/RushRoot/hf;->a(Lcom/kingroot/RushRoot/hi;IZ)Lcom/kingroot/RushRoot/hi;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     check-cast v0, Lcom/kingroot/RushRoot/gr;
a=0;// 
a=0;//     iput-object v0, p0, Lcom/kingroot/RushRoot/gs;->a:Lcom/kingroot/RushRoot/gr;
a=0;// 
a=0;//     .line 29
a=0;//     sget-object v0, Lcom/kingroot/RushRoot/gs;->d:[B
a=0;// 
a=0;//     if-nez v0, :cond_1
a=0;// 
a=0;//     .line 30
a=0;//     new-array v0, v1, [B
a=0;// 
a=0;//     .line 31
a=0;//     sput-object v0, Lcom/kingroot/RushRoot/gs;->d:[B
a=0;// 
a=0;//     aput-byte v2, v0, v2
a=0;// 
a=0;//     .line 34
a=0;//     :cond_1
a=0;//     sget-object v0, Lcom/kingroot/RushRoot/gs;->d:[B
a=0;// 
a=0;//     invoke-virtual {p1, v1, v1}, Lcom/kingroot/RushRoot/hf;->b(IZ)[B
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     iput-object v0, p0, Lcom/kingroot/RushRoot/gs;->b:[B
a=0;// 
a=0;//     .line 35
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public final a(Lcom/kingroot/RushRoot/hh;)V
a=0;//     .locals 2
a=0;// 
a=0;//     .prologue
a=0;//     .line 17
a=0;//     iget-object v0, p0, Lcom/kingroot/RushRoot/gs;->a:Lcom/kingroot/RushRoot/gr;
a=0;// 
a=0;//     #v0=(Reference,Lcom/kingroot/RushRoot/gr;);
a=0;//     const/4 v1, 0x0
a=0;// 
a=0;//     #v1=(Null);
a=0;//     invoke-virtual {p1, v0, v1}, Lcom/kingroot/RushRoot/hh;->a(Lcom/kingroot/RushRoot/hi;I)V
a=0;// 
a=0;//     .line 18
a=0;//     iget-object v0, p0, Lcom/kingroot/RushRoot/gs;->b:[B
a=0;// 
a=0;//     const/4 v1, 0x1
a=0;// 
a=0;//     #v1=(One);
a=0;//     invoke-virtual {p1, v0, v1}, Lcom/kingroot/RushRoot/hh;->a([BI)V
a=0;// 
a=0;//     .line 19
a=0;//     return-void
a=0;// .end method
}}
