package com.kingroot.RushRoot; class gt { void a() { int a;
a=0;// .class public final Lcom/kingroot/RushRoot/gt;
a=0;// .super Lcom/kingroot/RushRoot/hi;
a=0;// .source "SourceFile"
a=0;// 
a=0;// 
a=0;// # instance fields
a=0;// .field public a:I
a=0;// 
a=0;// .field public b:I
a=0;// 
a=0;// .field public c:I
a=0;// 
a=0;// 
a=0;// # direct methods
a=0;// .method public constructor <init>()V
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     const/4 v0, 0x0
a=0;// 
a=0;//     .line 18
a=0;//     #v0=(Null);
a=0;//     invoke-direct {p0}, Lcom/kingroot/RushRoot/hi;-><init>()V
a=0;// 
a=0;//     .line 14
a=0;//     #p0=(Reference,Lcom/kingroot/RushRoot/gt;);
a=0;//     iput v0, p0, Lcom/kingroot/RushRoot/gt;->a:I
a=0;// 
a=0;//     .line 15
a=0;//     iput v0, p0, Lcom/kingroot/RushRoot/gt;->b:I
a=0;// 
a=0;//     .line 16
a=0;//     iput v0, p0, Lcom/kingroot/RushRoot/gt;->c:I
a=0;// 
a=0;//     .line 19
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// 
a=0;// # virtual methods
a=0;// .method public final a(Lcom/kingroot/RushRoot/hf;)V
a=0;//     .locals 3
a=0;// 
a=0;//     .prologue
a=0;//     const/4 v2, 0x1
a=0;// 
a=0;//     .line 29
a=0;//     #v2=(One);
a=0;//     iget v0, p0, Lcom/kingroot/RushRoot/gt;->a:I
a=0;// 
a=0;//     #v0=(Integer);
a=0;//     invoke-virtual {p1, v0, v2, v2}, Lcom/kingroot/RushRoot/hf;->a(IIZ)I
a=0;// 
a=0;//     move-result v0
a=0;// 
a=0;//     iput v0, p0, Lcom/kingroot/RushRoot/gt;->a:I
a=0;// 
a=0;//     .line 30
a=0;//     iget v0, p0, Lcom/kingroot/RushRoot/gt;->b:I
a=0;// 
a=0;//     const/4 v1, 0x2
a=0;// 
a=0;//     #v1=(PosByte);
a=0;//     invoke-virtual {p1, v0, v1, v2}, Lcom/kingroot/RushRoot/hf;->a(IIZ)I
a=0;// 
a=0;//     move-result v0
a=0;// 
a=0;//     iput v0, p0, Lcom/kingroot/RushRoot/gt;->b:I
a=0;// 
a=0;//     .line 31
a=0;//     iget v0, p0, Lcom/kingroot/RushRoot/gt;->c:I
a=0;// 
a=0;//     const/4 v1, 0x3
a=0;// 
a=0;//     invoke-virtual {p1, v0, v1, v2}, Lcom/kingroot/RushRoot/hf;->a(IIZ)I
a=0;// 
a=0;//     move-result v0
a=0;// 
a=0;//     iput v0, p0, Lcom/kingroot/RushRoot/gt;->c:I
a=0;// 
a=0;//     .line 32
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public final a(Lcom/kingroot/RushRoot/hh;)V
a=0;//     .locals 2
a=0;// 
a=0;//     .prologue
a=0;//     .line 22
a=0;//     iget v0, p0, Lcom/kingroot/RushRoot/gt;->a:I
a=0;// 
a=0;//     #v0=(Integer);
a=0;//     const/4 v1, 0x1
a=0;// 
a=0;//     #v1=(One);
a=0;//     invoke-virtual {p1, v0, v1}, Lcom/kingroot/RushRoot/hh;->a(II)V
a=0;// 
a=0;//     .line 23
a=0;//     iget v0, p0, Lcom/kingroot/RushRoot/gt;->b:I
a=0;// 
a=0;//     const/4 v1, 0x2
a=0;// 
a=0;//     #v1=(PosByte);
a=0;//     invoke-virtual {p1, v0, v1}, Lcom/kingroot/RushRoot/hh;->a(II)V
a=0;// 
a=0;//     .line 24
a=0;//     iget v0, p0, Lcom/kingroot/RushRoot/gt;->c:I
a=0;// 
a=0;//     const/4 v1, 0x3
a=0;// 
a=0;//     invoke-virtual {p1, v0, v1}, Lcom/kingroot/RushRoot/hh;->a(II)V
a=0;// 
a=0;//     .line 25
a=0;//     return-void
a=0;// .end method
}}
