package com.kingroot.RushRoot; class hq { void a() { int a;
a=0;// .class public final Lcom/kingroot/RushRoot/hq;
a=0;// .super Ljava/lang/Object;
a=0;// .source "SourceFile"
a=0;// 
a=0;// 
a=0;// # instance fields
a=0;// .field public a:I
a=0;// 
a=0;// .field public b:I
a=0;// 
a=0;// .field public c:I
a=0;// 
a=0;// .field public d:I
a=0;// 
a=0;// .field public e:I
a=0;// 
a=0;// .field public f:I
a=0;// 
a=0;// .field public g:Z
a=0;// 
a=0;// .field public h:Z
a=0;// 
a=0;// .field public i:Ljava/lang/String;
a=0;// 
a=0;// .field public j:Ljava/lang/String;
a=0;// 
a=0;// .field public k:Ljava/lang/String;
a=0;// 
a=0;// 
a=0;// # direct methods
a=0;// .method public constructor <init>(IILjava/lang/String;Ljava/lang/String;Ljava/lang/String;)V
a=0;//     .locals 2
a=0;// 
a=0;//     .prologue
a=0;//     const/4 v1, 0x0
a=0;// 
a=0;//     .line 29
a=0;//     #v1=(Null);
a=0;//     invoke-direct {p0}, Ljava/lang/Object;-><init>()V
a=0;// 
a=0;//     .line 19
a=0;//     #p0=(Reference,Lcom/kingroot/RushRoot/hq;);
a=0;//     iput v1, p0, Lcom/kingroot/RushRoot/hq;->f:I
a=0;// 
a=0;//     .line 32
a=0;//     iput v1, p0, Lcom/kingroot/RushRoot/hq;->a:I
a=0;// 
a=0;//     .line 33
a=0;//     iput v1, p0, Lcom/kingroot/RushRoot/hq;->b:I
a=0;// 
a=0;//     .line 34
a=0;//     iput p1, p0, Lcom/kingroot/RushRoot/hq;->c:I
a=0;// 
a=0;//     .line 35
a=0;//     iput p2, p0, Lcom/kingroot/RushRoot/hq;->d:I
a=0;// 
a=0;//     .line 36
a=0;//     const/4 v0, -0x1
a=0;// 
a=0;//     #v0=(Byte);
a=0;//     iput v0, p0, Lcom/kingroot/RushRoot/hq;->e:I
a=0;// 
a=0;//     .line 37
a=0;//     const/4 v0, 0x2
a=0;// 
a=0;//     #v0=(PosByte);
a=0;//     iput v0, p0, Lcom/kingroot/RushRoot/hq;->f:I
a=0;// 
a=0;//     .line 38
a=0;//     const/4 v0, 0x1
a=0;// 
a=0;//     #v0=(One);
a=0;//     iput-boolean v0, p0, Lcom/kingroot/RushRoot/hq;->h:Z
a=0;// 
a=0;//     .line 39
a=0;//     iput-boolean v1, p0, Lcom/kingroot/RushRoot/hq;->g:Z
a=0;// 
a=0;//     .line 40
a=0;//     iput-object p3, p0, Lcom/kingroot/RushRoot/hq;->i:Ljava/lang/String;
a=0;// 
a=0;//     .line 41
a=0;//     iput-object p4, p0, Lcom/kingroot/RushRoot/hq;->j:Ljava/lang/String;
a=0;// 
a=0;//     .line 42
a=0;//     iput-object p5, p0, Lcom/kingroot/RushRoot/hq;->k:Ljava/lang/String;
a=0;// 
a=0;//     .line 43
a=0;//     return-void
a=0;// .end method
}}
