package com.kingroot.RushRoot; class KrApplication { void a() { int a;
a=0;// .class public Lcom/kingroot/RushRoot/KrApplication;
a=0;// .super Landroid/app/Application;
a=0;// .source "SourceFile"
a=0;// 
a=0;// 
a=0;// # static fields
a=0;// .field private static a:Landroid/content/Context;
a=0;// 
a=0;// 
a=0;// # direct methods
a=0;// .method public constructor <init>()V
a=0;//     .locals 0
a=0;// 
a=0;//     .prologue
a=0;//     .line 10
a=0;//     invoke-direct {p0}, Landroid/app/Application;-><init>()V
a=0;// 
a=0;//     #p0=(Reference,Lcom/kingroot/RushRoot/KrApplication;);
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public static a()Landroid/content/Context;
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 53
a=0;//     sget-object v0, Lcom/kingroot/RushRoot/KrApplication;->a:Landroid/content/Context;
a=0;// 
a=0;//     #v0=(Reference,Landroid/content/Context;);
a=0;//     return-object v0
a=0;// .end method
a=0;// 
a=0;// .method public static a(Landroid/content/Context;)V
a=0;//     .locals 0
a=0;// 
a=0;//     .prologue
a=0;//     .line 57
a=0;//     sput-object p0, Lcom/kingroot/RushRoot/KrApplication;->a:Landroid/content/Context;
a=0;// 
a=0;//     .line 58
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method static synthetic b()Landroid/content/Context;
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 10
a=0;//     sget-object v0, Lcom/kingroot/RushRoot/KrApplication;->a:Landroid/content/Context;
a=0;// 
a=0;//     #v0=(Reference,Landroid/content/Context;);
a=0;//     return-object v0
a=0;// .end method
a=0;// 
a=0;// 
a=0;// # virtual methods
a=0;// .method public onCreate()V
a=0;//     .locals 2
a=0;// 
a=0;//     .prologue
a=0;//     const/4 v1, 0x0
a=0;// 
a=0;//     .line 17
a=0;//     #v1=(Null);
a=0;//     invoke-super {p0}, Landroid/app/Application;->onCreate()V
a=0;// 
a=0;//     .line 21
a=0;//     invoke-virtual {p0}, Lcom/kingroot/RushRoot/KrApplication;->getApplicationContext()Landroid/content/Context;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     #v0=(Reference,Landroid/content/Context;);
a=0;//     sput-object v0, Lcom/kingroot/RushRoot/KrApplication;->a:Landroid/content/Context;
a=0;// 
a=0;//     .line 23
a=0;//     invoke-static {p0, v1, v1}, Lcom/kingroot/RushRoot/ak;->a(Landroid/content/Context;Ljava/lang/String;Ljava/lang/String;)V
a=0;// 
a=0;//     .line 25
a=0;//     invoke-static {p0}, Lcom/kingroot/RushRoot/x;->a(Landroid/content/Context;)V
a=0;// 
a=0;//     .line 27
a=0;//     invoke-static {p0}, Lcom/kingroot/RushRoot/y;->a(Landroid/content/Context;)V
a=0;// 
a=0;//     .line 30
a=0;//     invoke-static {}, Lcom/kingroot/RushRoot/statics/a;->a()Lcom/kingroot/RushRoot/statics/a;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     invoke-virtual {v0}, Lcom/kingroot/RushRoot/statics/a;->c()V
a=0;// 
a=0;//     .line 31
a=0;//     invoke-static {}, Lcom/kingroot/RushRoot/statics/a;->a()Lcom/kingroot/RushRoot/statics/a;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     invoke-virtual {v0}, Lcom/kingroot/RushRoot/statics/a;->h()V
a=0;// 
a=0;//     .line 32
a=0;//     new-instance v0, Lcom/kingroot/RushRoot/w;
a=0;// 
a=0;//     #v0=(UninitRef,Lcom/kingroot/RushRoot/w;);
a=0;//     invoke-direct {v0, p0}, Lcom/kingroot/RushRoot/w;-><init>(Lcom/kingroot/RushRoot/KrApplication;)V
a=0;// 
a=0;//     #v0=(Reference,Lcom/kingroot/RushRoot/w;);
a=0;//     invoke-virtual {v0}, Lcom/kingroot/RushRoot/w;->a()Z
a=0;// 
a=0;//     .line 41
a=0;//     invoke-static {p0}, Lcom/kingroot/RushRoot/ae;->a(Landroid/content/Context;)Lcom/kingroot/RushRoot/ae;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     invoke-virtual {v0}, Lcom/kingroot/RushRoot/ae;->c()V
a=0;// 
a=0;//     .line 45
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public onTerminate()V
a=0;//     .locals 0
a=0;// 
a=0;//     .prologue
a=0;//     .line 49
a=0;//     invoke-super {p0}, Landroid/app/Application;->onTerminate()V
a=0;// 
a=0;//     .line 50
a=0;//     return-void
a=0;// .end method
}}
