package com.kingroot.RushRoot.activities; class c { void a() { int a;
a=0;// .class final Lcom/kingroot/RushRoot/activities/c;
a=0;// .super Ljava/lang/Object;
a=0;// .source "SourceFile"
a=0;// 
a=0;// # interfaces
a=0;// .implements Landroid/view/View$OnClickListener;
a=0;// 
a=0;// 
a=0;// # instance fields
a=0;// .field final synthetic a:Lcom/kingroot/RushRoot/activities/MainActivity;
a=0;// 
a=0;// 
a=0;// # direct methods
a=0;// .method constructor <init>(Lcom/kingroot/RushRoot/activities/MainActivity;)V
a=0;//     .locals 0
a=0;// 
a=0;//     .prologue
a=0;//     .line 70
a=0;//     iput-object p1, p0, Lcom/kingroot/RushRoot/activities/c;->a:Lcom/kingroot/RushRoot/activities/MainActivity;
a=0;// 
a=0;//     invoke-direct {p0}, Ljava/lang/Object;-><init>()V
a=0;// 
a=0;//     #p0=(Reference,Lcom/kingroot/RushRoot/activities/c;);
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// 
a=0;// # virtual methods
a=0;// .method public final onClick(Landroid/view/View;)V
a=0;//     .locals 2
a=0;// 
a=0;//     .prologue
a=0;//     .line 73
a=0;//     iget-object v0, p0, Lcom/kingroot/RushRoot/activities/c;->a:Lcom/kingroot/RushRoot/activities/MainActivity;
a=0;// 
a=0;//     #v0=(Reference,Lcom/kingroot/RushRoot/activities/MainActivity;);
a=0;//     invoke-static {v0}, Lcom/kingroot/RushRoot/ae;->a(Landroid/content/Context;)Lcom/kingroot/RushRoot/ae;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     const/4 v1, 0x0
a=0;// 
a=0;//     #v1=(Null);
a=0;//     invoke-virtual {v0, v1}, Lcom/kingroot/RushRoot/ae;->startRoot(Z)V
a=0;// 
a=0;//     .line 75
a=0;//     invoke-static {}, Lcom/kingroot/RushRoot/statics/a;->a()Lcom/kingroot/RushRoot/statics/a;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     invoke-virtual {v0}, Lcom/kingroot/RushRoot/statics/a;->d()V
a=0;// 
a=0;//     .line 76
a=0;//     invoke-static {}, Lcom/kingroot/RushRoot/statics/a;->a()Lcom/kingroot/RushRoot/statics/a;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     invoke-virtual {v0}, Lcom/kingroot/RushRoot/statics/a;->h()V
a=0;// 
a=0;//     .line 77
a=0;//     return-void
a=0;// .end method
}}
